name: Build
'on':
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  dotnet6:
    name: .NET6
    runs-on: ubuntu-latest
    steps:
      - uses: AutoModality/action-clean@v1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
    dotnet7:
      name: .NET7
      runs-on: ubuntu-latest
      steps:
        - uses: AutoModality/action-clean@v1
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 7.0.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore
        - name: Test
          run: dotnet test --no-build --verbosity normal
